import layoutImg from "../../assets/images/layoutimg.png"
import TechImg from "../../assets/images/techimg.png"
import RiverImg from "../../assets/images/riverside.png"
import greenImg from "../../assets/images/greenimg.png"
import LogisImg from "../../assets/images/logisimg.png"
import CoastalImg from "../../assets/images/coastal.png"

export const investments = [
  {
    image: layoutImg,
    status: 'Ongoing',
    id: 'INV-001',
    title: 'Downtown Luxury Residences',
    investors: 156,
    description: 'Premium residential complex in the heart of downtown with modern amenities and high rental yield potential.',
    investmentValue: '$850,000',
    roiLabel: 'Expected ROI',
    roi: '14.2%',
    duration: '24 months',
    category: 'Real Estate',
    packageType: '1',
    price1: '₦850,000',
    price2: '₦400,000',
    duration1: '24 months',
    duration2: '12 months',
    roi1: '14.2% ROI',
    roi2: '7% ROI',
  },
  {
    image: TechImg,
    status: 'Ongoing',
    id: 'INV-002',
    title: 'Tech Hub Office Complex',
    investors: 156,
    description: 'State-of-the-art office spaces designed for technology companies with flexible layouts and smart building features.',
    investmentValue: '$1,200,000',
    roiLabel: 'Expected ROI',
    roi: '16.8%',
    duration: '36 months',
    category: 'Commercial',
    packageType: '2',
    price1: '₦1,200,000',
    price2: '₦600,000',
    duration1: '36 months',
    duration2: '18 months',
    roi1: '16.8% ROI',
    roi2: '9% ROI',
  },
  {
    image: RiverImg,
    status: 'Closed',
    id: 'INV-003',
    title: 'Riverside Mixed Development',
    investors: 156,
    description: 'Integrated development combining retail, residential, and entertainment spaces along the waterfront.',
    investmentValue: '$2,100,000',
    roiLabel: 'Expected ROI',
    roi: '18.5%',
    duration: '48 months',
    category: 'Mixed Use',
    packageType: '1',
    price1: '₦2,100,000',
    price2: '₦900,000',
    duration1: '48 months',
    duration2: '24 months',
    roi1: '18.5% ROI',
    roi2: '10% ROI',
  },
  {
    image: greenImg,
    status: 'Closed',
    id: 'INV-004',
    title: 'Green Valley Homes',
    investors: 156,
    description: 'Sustainable residential community featuring energy-efficient homes and eco-friendly amenities.',
    investmentValue: '$950,000',
    roiLabel: 'Expected ROI',
    roi: '13.7%',
    duration: '30 months',
    category: 'Residential',
    packageType: '1',
    price1: '₦950,000',
    price2: '₦400,000',
    duration1: '30 months',
    duration2: '15 months',
    roi1: '13.7% ROI',
    roi2: '7% ROI',
  },
  {
    image: LogisImg,
    status: 'Ongoing',
    id: 'INV-005',
    title: 'Logistics Hub Center',
    investors: 156,
    description: 'Strategic logistics and distribution center positioned near major transportation corridors.',
    investmentValue: '$1,750,000',
    roiLabel: 'Expected ROI',
    roi: '15.3%',
    duration: '42 months',
    category: 'Industrial',
    packageType: '2',
    price1: '₦1,750,000',
    price2: '₦800,000',
    duration1: '42 months',
    duration2: '21 months',
    roi1: '15.3% ROI',
    roi2: '8% ROI',
  },
  {
    image: CoastalImg,
    status: 'Closed',
    id: 'INV-006',
    title: 'Coastal Resort Development',
    investors: 156,
    description: 'Luxury resort and spa facility with premium accommodations and world-class amenities.',
    investmentValue: '$3,200,000',
    roiLabel: 'Achieved ROI',
    roi: '19.2%',
    duration: '60 months',
    category: 'Hospitality',
    packageType: '1',
    price1: '₦3,200,000',
    price2: '₦1,500,000',
    duration1: '60 months',
    duration2: '30 months',
    roi1: '19.2% ROI',
    roi2: '11% ROI',
  },
]